### ISSUE TITLE
blog,twitterへのリンク

### ISSUE THREAD

**Issue by hiro0412** [pycon-mini-osaka/pycon-mini-osaka.github.io#10]
以下へのリンクをつけましょう

- blog: http://pyconjp.blogspot.jp/  （でいいか？
- twitter: https://twitter.com/OsakaPyConMini

**Comment by Akira-Taniguchi** [comment]
ブログは全体リンクではなく、PyCon mini Osakaの個別ブログでいいのでは？
http://pyconjp.blogspot.jp/2018/02/pycon-mini-osaka-2018.html

で、今後なにか書く度に記述していけば

**Comment by hiro0412** [comment]
> ブログは全体リンクではなく、PyCon mini Osakaの個別ブログでいいのでは？
> http://pyconjp.blogspot.jp/2018/02/pycon-mini-osaka-2018.html

よくわかってないんですが、PyconMiniOsaka2018に関する記事はこの記事に追加されていく感じでしょうか？（URLが2018/02になってるし、blogの体裁だとちと不自然な気もしました）

全体だとそれ以外の記事も見えるのでわかりにくくなる　というのはあると思います。
タグとかカテゴリとかでPyconMiniOsaka関連の記事だけ絞り込メルようになっているといいんですが・・・

**Comment by Akira-Taniguchi** [comment]
ほんまっすね

http://pyconjp.blogspot.jp/search/label/pyconmini

というわｋで、pyconmini のタグがあるブログが引っ張ってくれるURLがこれになりますので、
これをサイトにいい感じで貼ればいいのでわと

**Comment by Akira-Taniguchi** [comment]
そしてこれからかくブログにはpyconminiのタグはっとけばいい

**Comment by RossyWhite** [comment]
@Akira-Taniguchi 

確認おなしゃす。

**Comment by Akira-Taniguchi** [comment]
マージした。動作はするけど、ボタンが黄色くなってないっす。
俺だけ？

@RossyWhite

**Comment by RossyWhite** [comment]
@Akira-Taniguchi 

僕は問題ないです。
cssがキャッシュされてないですか?

**Comment by Akira-Taniguchi** [comment]
されていました
