### ISSUE TITLE
CfPの応募状況をサイトに記載する

### ISSUE THREAD

**Issue by Akira-Taniguchi** [pycon-mini-osaka/pycon-mini-osaka.github.io#11]
現在のCfPの応募状況をサイトに記載して欲しいです。
目的は集まってる感、動いてる感を演出し、サイト訪問者を煽るため

トータル件数は6件

内訳は
Fintech 1件
Core python
Best Practice 1件
Big Dataが1件
Otherが2件
であることをどこかに書いていただければと

**Comment by Akira-Taniguchi** [comment]
@RossyWhite 
すまぬ、Otherが3つあるのだが、はんえいされておらず。

**Comment by RossyWhite** [comment]
@Akira-Taniguchi 
:+1:
