### ISSUE TITLE
サイトにスポンサーのロゴをのっける

### ISSUE THREAD

**Issue by Akira-Taniguchi** [pycon-mini-osaka/pycon-mini-osaka.github.io#13]
![techlogo_500x500](https://user-images.githubusercontent.com/16591967/36955430-d4aaf376-206b-11e8-9819-367dd7e2acbb.png)

よういしたので、お願いします。
もっと違うサイズがいいとか、そういうのあればまた連絡ください

@RossyWhite

**Comment by RossyWhite** [comment]
tech bureau DONE
