### ISSUE TITLE
スマホ画面でロゴの縦横比がおかしい

### ISSUE THREAD

**Issue by RossyWhite** [pycon-mini-osaka/pycon-mini-osaka.github.io#2]
![2018-02-03 21 16 20](https://user-images.githubusercontent.com/16730512/35767046-98fdfe1e-0927-11e8-8914-f0ee3c2fa244.png)

**Comment by bulbulpaul** [comment]
修正の反映がされたのでクローズしますmm
![image](https://user-images.githubusercontent.com/6457054/35838147-3cb4caea-0b2d-11e8-9a02-2d937e42559f.png)
