### ISSUE TITLE
meta情報がほしい

### ISSUE THREAD

**Issue by Akira-Taniguchi** [pycon-mini-osaka/pycon-mini-osaka.github.io#5]
Akira Taniguchi [10:53 AM]
http://osaka.pycon.jp/
pycon mini osakaのロゴの評判がすこぶるよくてうれしい (edited)

Takanori Suzuki [11:30 AM]
metaにdescriptionとかog:imageとかないので、なにも展開されないのでSlackにはるとさびしい

Akira Taniguchi [11:39 AM]
なるほど

**Comment by Akira-Taniguchi** [comment]
@RossyWhite おねがいしていいですかね

**Comment by Akira-Taniguchi** [comment]
<meta property="og:title" content="DjangoCongress JP 2018" />
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://djangocongress.jp/">
    <meta property="og:description" content="DjangoCongress JP は日本で開催されるDjango Webフレームワークのカンファレンスです. DjangoCongress JP is a conference for the Django Web framework in Japan. ">
    <meta property="og:image" content="https://djangocongress.jp/assets/img/ogp.png">

上記はジャンゴカンファレンスの例

@RossyWhite

**Comment by RossyWhite** [comment]
@Akira-Taniguchi 

👍
